project:
  type: website
  output-dir: docs

website:
  title: "2024 DSAN Bootcamp Videos"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
        icon: "home"

format:
  html:
    theme: default
    css: styles.css
    toc: true
