project:
  type: website
  output-dir: docs

website:
  title: "2024 DSAN Bootcamp Videos"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: default
    css: styles.css
    toc: true
