---
title: "Bootcamp Week 6"
format: html
---

Welcome to Week 6 of the 2024 DSAN Bootcamp! This week we will be covering the following topics:

* W06.1: [Introduction to Quarto](#part-1-introduction-to-quarto)
* W06.2: Installing Quarto ([OSX](#part-2a-installing-quarto-on-macos) and [Windows](#part-2b-installing-quarto-on-windows))
* W06.3: [Vectors, Data Frames, Filtering, Sampling](#part-3-introduction-to-r)

## Lectures

### Part 1: Introduction to Quarto

[**Click to open slides in a separate tab** <i class='bi bi-box-arrow-up-right ps-1'></i>](https://jjacobs.me/bootcamp-videos/w06-1/slides.html#/title-slide){target='_blank' style='font-size: 120%;'}

<iframe src="https://georgetown.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=8ffaeb43-53d7-4d69-8f1d-b1760007b1ae&autoplay=false&offerviewer=true&showtitle=true&showbrand=false&captions=true&interactivity=all" height="380" width="100%" style="border: 1px solid #464646;" allowfullscreen aria-label="Panopto Embedded Video Player" aria-description="DSAN Bootcamp 2024 W6.1: Introduction to Quarto" ></iframe>

### Part 2a: Installing Quarto on macOS

<iframe src="https://georgetown.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=7f9cabc7-e8c9-4e3c-9990-b176005fcc6d&autoplay=false&offerviewer=true&showtitle=true&showbrand=false&captions=true&interactivity=all" height="380" width="100%" style="border: 1px solid #464646;" allowfullscreen aria-label="Panopto Embedded Video Player" aria-description="DSAN Bootcamp 2024 W6.2a: Installing Quarto on macOS" ></iframe>

### Part 2b: Installing Quarto on Windows

<iframe src="https://georgetown.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=3704d9ab-db6e-4516-b73e-b178015af7d7&autoplay=false&offerviewer=true&showtitle=true&showbrand=false&captions=true&interactivity=all" height="380" width="100%" style="border: 1px solid #464646;" allowfullscreen aria-label="Panopto Embedded Video Player" aria-description="DSAN Bootcamp 2024 W6.2b: Installing Quarto on Windows" ></iframe>

### Part 3: Introduction to R

[**Click to open slides in a separate tab** <i class='bi bi-box-arrow-up-right ps-1'></i>](https://jjacobs.me/bootcamp-videos/w06-3/slides.html#/title-slide){target='_blank' style='font-size: 120%;'}

<iframe src="https://georgetown.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=ee363df9-0db9-47f8-a4a3-b180002e0fe8&autoplay=false&offerviewer=true&showtitle=true&showbrand=false&captions=true&interactivity=all" height="380" width="100%" style="border: 1px solid #464646;" allowfullscreen aria-label="Panopto Embedded Video Player" aria-description="DSAN Bootcamp 2024 W6.3: Introduction to R" ></iframe>

## Assignment

Once you have digested the lectures, you will be able to do the assignment for week 6!

* To **preview** the assignment, [click here](./w06-assignment.qmd)
* Once you're ready to begin working on it, however, you should [**download** the `.zip` file](./w06-assignment.zip){target='_blank'}, which contains both the assignment `.qmd` file and the required data files.

For submission:

1. Please create a separate directory for each assignment in your computer.
2. Render the answers to html OR pdf with the filename `YOUR_NAME_Assignment_6`
3. Please submit this inside a `.zip` file named `FIRSTNAME_LASTNAME_Assignment_6.zip`. For example: `JANE_DOE_Assignment_6.zip`
4. Please DO NOT send the `.qmd` file. If you can't render the `.qmd` file to HTML or PDF then that means there might be an error. Please fix it and only send the rendered version of the `.qmd` file.
5. Please email the rendered file in `.zip` format to your TA only.
